# Generated by Django 4.2.1 on 2023-05-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='mymodel',
            field=models.CharField(help_text='Ingrese un genero del libro', max_length=200),
        ),
    ]
