# Generated by Django 4.2.1 on 2023-05-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_genre_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='mymodel',
            new_name='Genre',
        ),
    ]
