# Generated by Django 4.2.1 on 2023-05-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_mymodel_genre_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='Book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.book'),
        ),
    ]
