# Generated by Django 4.2.1 on 2023-05-16 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_bookinstance_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='Genre',
            new_name='genre',
        ),
    ]
