# Generated by Django 4.2.1 on 2023-05-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_book_bookinstance_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='book',
            new_name='Book',
        ),
    ]
